### ISSUE TITLE
Backend repo not found

### ISSUE THREAD

**Issue by abdulkader00** [tks18/gindex-v4#225]
In your installation guide you put a backend server's repo link but it now not working.

**Comment by tks18** [comment]
Use The wiki in my repo to see my latest gindex cli tool

(Sent from Mobile)

**Comment by abdulkader00** [comment]
✔ Enter You Name · abdulkader00

Hello there abdulkader00 !!


Git Status
Git is Available and Version: git version 2.30.0


NPM Status
NPM is Available and Version: 6.14.10

  D Checking Heroku Global Status and Version


It's in an infinite loop in Checking Heroku Global Status and Version

It's not going any where

**Comment by abdulkader00** [comment]
Even though I used your latest cli app got crushed. It's not working. I am attaching log of my app. If you can please have a look


2021-02-08T17:22:19.367783+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-02-08T17:22:19.367784+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2021-02-08T17:22:19.367784+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-02-08T17:22:19.367943+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2021-02-08T17:22:19.368062+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-02-08T17:22:19.585879+00:00 heroku[web.1]: State changed from starting to up
2021-02-08T17:23:13.505567+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=testbot245.herokuapp.com request_id=0793cd43-c3b8-40a6-9a73-f8525ff5425a fwd="110.76.128.84" dyno=web.1 connect=2ms service=30001ms status=503 bytes=0 protocol=https
2021-02-08T17:23:15.182421+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=testbot245.herokuapp.com request_id=56b8d9a3-fda6-48ea-b946-41454193d808 fwd="110.76.128.84" dyno=web.1 connect=2ms service=11ms status=404 bytes=426 protocol=https
2021-02-08T17:24:12.009007+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=testbot245.herokuapp.com request_id=e25f3906-195c-4b0f-9656-7d82a700a697 fwd="110.76.128.84" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2021-02-08T17:25:41.107305+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=testbot245.herokuapp.com request_id=1900994e-5887-4a67-ac3f-bd49a08bf38f fwd="110.76.128.84" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

**Comment by tks18** [comment]
Your dburl is wrong, Did you use any special characters In the mongodb password, if used then change that password in mongodb and change in heroku also

**Comment by abdulkader00** [comment]
No I didn't put any special characters. My password is just alphabet and numbers.

mongodb+srv://abdulkader000:abdulkader6783@cluster0.1p4up.mongodb.net/MyUsers?retryWrites=true&w=majority

Is this format okay?

**Comment by saveitlol** [comment]
![error](https://user-images.githubusercontent.com/53550696/107925950-af86ca00-6fa7-11eb-8473-82ccedd59800.PNG

I run "gdployer init" and get the error message, how do I fix it?

**Comment by tks18** [comment]
Will try resolving this.

With Regards,
Sudharshan TK

(Sent from Mobile)
