### ISSUE TITLE
I am not getting the email to register a user.

### ISSUE THREAD

**Issue by oneironaut2209** [tks18/gindex-v4#254]
2021-05-26T07:42:11.980874+00:00 app[web.1]: Request Not Found
2021-05-26T07:42:12.423410+00:00 app[web.1]: Error: Invalid login: 535 5.7.0 (#AUTH005) Too many bad auth attempts.
2021-05-26T07:42:12.423427+00:00 app[web.1]:     at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
2021-05-26T07:42:12.423428+00:00 app[web.1]:     at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
2021-05-26T07:42:12.423429+00:00 app[web.1]:     at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:550:26)
2021-05-26T07:42:12.423429+00:00 app[web.1]:     at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
2021-05-26T07:42:12.423429+00:00 app[web.1]:     at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
2021-05-26T07:42:12.423430+00:00 app[web.1]:     at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
2021-05-26T07:42:12.423431+00:00 app[web.1]:     at TLSSocket.emit (events.js:376:20)
2021-05-26T07:42:12.423432+00:00 app[web.1]:     at addChunk (internal/streams/readable.js:309:12)
2021-05-26T07:42:12.423432+00:00 app[web.1]:     at readableAddChunk (internal/streams/readable.js:284:9)
2021-05-26T07:42:12.423432+00:00 app[web.1]:     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
2021-05-26T07:42:12.423433+00:00 app[web.1]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
2021-05-26T07:42:12.423433+00:00 app[web.1]:   code: 'EAUTH',
2021-05-26T07:42:12.423434+00:00 app[web.1]:   response: '535 5.7.0 (#AUTH005) Too many bad auth attempts.',
2021-05-26T07:42:12.423434+00:00 app[web.1]:   responseCode: 535,
2021-05-26T07:42:12.423434+00:00 app[web.1]:   command: 'AUTH PLAIN'
2021-05-26T07:42:12.423435+00:00 app[web.1]: }
2021-05-26T07:42:12.424957+00:00 app[web.1]: Error: Invalid login: 535 5.7.0 (#AUTH005) Too many bad auth attempts.
2021-05-26T07:42:12.424958+00:00 app[web.1]:     at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
2021-05-26T07:42:12.424958+00:00 app[web.1]:     at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
2021-05-26T07:42:12.424959+00:00 app[web.1]:     at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:550:26)
2021-05-26T07:42:12.424959+00:00 app[web.1]:     at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
2021-05-26T07:42:12.424959+00:00 app[web.1]:     at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
2021-05-26T07:42:12.424960+00:00 app[web.1]:     at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
2021-05-26T07:42:12.424960+00:00 app[web.1]:     at TLSSocket.emit (events.js:376:20)
2021-05-26T07:42:12.424961+00:00 app[web.1]:     at addChunk (internal/streams/readable.js:309:12)
2021-05-26T07:42:12.424961+00:00 app[web.1]:     at readableAddChunk (internal/streams/readable.js:284:9)
2021-05-26T07:42:12.424961+00:00 app[web.1]:     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
2021-05-26T07:42:12.424961+00:00 app[web.1]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
2021-05-26T07:42:12.424962+00:00 app[web.1]:   code: 'EAUTH',
2021-05-26T07:42:12.424962+00:00 app[web.1]:   response: '535 5.7.0 (#AUTH005) Too many bad auth attempts.',
2021-05-26T07:42:12.424962+00:00 app[web.1]:   responseCode: 535,
2021-05-26T07:42:12.424962+00:00 app[web.1]:   command: 'AUTH PLAIN'
2021-05-26T07:42:12.424963+00:00 app[web.1]: }

Heroku logs

**Comment by tks18** [comment]
It looks like your email credentials are wrong 
Recheck it once
Also check whether your mail provider requires a app password

**Comment by TargetX25** [comment]
which mail provider is works correctly for this code? Any preference

**Comment by tks18** [comment]
You can connect any email with a smtp api provider like sendgrid

With that you can send emails from our app
